In [20]:
import pandas as pd

data = pd.read_csv('RandData1.csv')
data

,Age,Gender,Place of Stay,Relationship status,No of dependents,Monthly pocketmoney,Monthly exp on transport,Monthly exp on food,Monthly exp on education,notable investments,...,how often do you make impulse purchases?,"do you currently invest in any financial products like stocks,mutual funds or cryptocurrencies",how comfortable are you with taking financial risk in your investments,Do you use any mobile apps or online platforms to manage your finances and investments,Expenses on fresh groceries and whole foods.,expenses on online takeout,expenditure on medicine,expenses on outings,tax payments,what types of food do u spen money on
0,21,0,1,0,5,10000,8000,4200,2100,1100,...,2,0,0,1,1400,2900,500,10000,1000,5
1,21,0,0,0,1,8000,5800,3700,1900,1300,...,1,0,0,0,200,1900,400,10000,3000,4
2,21,0,0,0,4,9000,2500,800,1800,2800,...,1,1,0,1,500,3600,500,4000,3000,4
3,22,1,0,1,1,5000,3100,200,1200,2100,...,1,0,0,1,600,3500,2300,7000,2000,5
4,19,0,0,2,3,7000,3400,4400,1500,2300,...,0,1,1,1,200,2100,2400,4000,5000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,21,1,0,1,4,4000,6300,2300,2300,800,...,1,1,1,1,1200,2600,2600,1000,3000,2
195,19,1,1,1,4,4000,4500,4700,1100,0,...,1,0,1,1,1000,600,1700,5000,0,3
196,21,1,0,1,5,8000,100,3200,100,2000,...,1,0,0,0,500,1100,300,0,4000,3
197,22,1,0,1,5,4000,7900,1100,900,1300,...,1,1,0,0,1500,1700,300,2000,2000,3
198,21,1,0,0,1,5000,3900,2800,800,2100,...,2,1,0,0,500,3000,300,6000,2000,5

In [21]:
new_data = data.head(1)
new_data

,Age,Gender,Place of Stay,Relationship status,No of dependents,Monthly pocketmoney,Monthly exp on transport,Monthly exp on food,Monthly exp on education,notable investments,...,how often do you make impulse purchases?,"do you currently invest in any financial products like stocks,mutual funds or cryptocurrencies",how comfortable are you with taking financial risk in your investments,Do you use any mobile apps or online platforms to manage your finances and investments,Expenses on fresh groceries and whole foods.,expenses on online takeout,expenditure on medicine,expenses on outings,tax payments,what types of food do u spen money on
0,21,0,1,0,5,10000,8000,4200,2100,1100,...,2,0,0,1,1400,2900,500,10000,1000,5

In [25]:
print(new_data)

   Age  Gender  Place of Stay  Relationship status  No of dependents  \
0   21       0              1                    0                 5

   Monthly pocketmoney  Monthly exp on transport  Monthly exp on food  \
0                10000                      8000                 4200

   Monthly exp on education  notable investments  ...  \
0                      2100                 1100  ...

   how often do you make impulse purchases?  \
0                                         2

   do you currently invest in any financial products like stocks,mutual funds or cryptocurrencies  \
0                                                  0

   how comfortable are you with taking financial risk in your investments  \
0                                                  0

   Do you use any mobile apps or online platforms to manage your finances and investments  \
0                                                  1

   Expenses on fresh groceries and whole foods.  expenses on online takeout  \
0                                          1400                        2900

   expenditure on medicine  expenses on outings  tax payments  \
0                      500                10000          1000

   what types of food do u spen money on
0                                      5

[1 rows x 26 columns]

In [ ]:
#creating data and spitting numerica and categorical


data['Total Expenses'] = data['Monthly exp on transport'] + data['Monthly exp on food'] + \
                         data['Monthly exp on education'] + data['expenses on online takeout'] + \
                         data['expenditure on medicine'] + data['expenses on outings'] + \
                         data['Expenses on fresh groceries and whole foods.']


numeric_features = ['Age', 'Monthly pocketmoney', 'Monthly exp on transport', 'Monthly exp on food', 
                    'Monthly exp on education', 'Debt', 
                    'Expenses on fresh groceries and whole foods.', 'expenses on online takeout', 
                    'expenditure on medicine', 'expenses on outings', 'tax payments', 'Total Expenses']

categorical_features = ['Gender', 'Place of Stay', 'Relationship status', 'notable investments',
                        'Financial goals', 'Do you follow a monthly budget ?', 'how often do u dine out?',
                        'how often do you make impulse purchases?', 
                        'do you currently invest in any financial products like stocks,mutual funds or cryptocurrencies',
                        'how comfortable are you with taking financial risk in your investments', 
                        'Do you use any mobile apps or online platforms to manage your finances and investments']

In [38]:
data.shape

(199, 27)

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np

scale = StandardScaler()
processed_data = scale.fit_transform(data)

data['Recommended Actions'] = np.random.choice([1, 2, 3, 4], size=len(data))

X = processed_data
y = data['Recommended Actions']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [23]:
from sklearn.metrics import classification_report, accuracy_score

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier


model = GradientBoostingClassifier(random_state=42)

param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7]
}

In [24]:
# Grid search CV
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Best model
best_model = grid_search.best_estimator_
print(f"Best parameters: {grid_search.best_params_}")

Best parameters: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 200}

In [33]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")


print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

              precision    recall  f1-score   support

           1       0.30      0.25      0.27        12
           2       0.50      0.41      0.45        17
           3       0.00      0.00      0.00         4
           4       0.43      0.35      0.39        17

    accuracy                           0.32        50
   macro avg       0.31      0.25      0.28        50
weighted avg       0.39      0.32      0.35        50

Accuracy: 0.32
              precision    recall  f1-score   support

           1       0.30      0.25      0.27        12
           2       0.50      0.41      0.45        17
           3       0.00      0.00      0.00         4
           4       0.43      0.35      0.39        17

    accuracy                           0.32        50
   macro avg       0.31      0.25      0.28        50
weighted avg       0.39      0.32      0.35        50

Accuracy: 0.32

In [34]:
import joblib

joblib.dump(best_model,'RS.pkl')

['RS.pkl']

In [35]:
model = joblib.load('RS.pkl')
model

GradientBoostingClassifier(learning_rate=0.2, n_estimators=200, random_state=42)

In [37]:
result = model.predict(new_data)
print(result)

[4]

C:\Users\user\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but GradientBoostingClassifier was fitted without feature names
  warnings.warn(